-- Add SpySERP config to websites
ALTER TABLE websites ADD COLUMN IF NOT EXISTS spyserp_project_id BIGINT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS spyserp_domain_id BIGINT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS spyserp_folder_name TEXT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS spyserp_valuemetric_id BIGINT;
ALTER TABLE websites ADD COLUMN IF NOT EXISTS spyserp_engine_id BIGINT;

-- Create seo_keywords table
CREATE TABLE IF NOT EXISTS seo_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    website_id UUID REFERENCES websites(uuid) ON DELETE CASCADE,
    keyword TEXT NOT NULL,
    spyserp_key_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(website_id, keyword)
);

-- Create seo_daily_ranks table
CREATE TABLE IF NOT EXISTS seo_daily_ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id BIGINT REFERENCES seo_keywords(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    position INT,
    url TEXT,
    engine_id BIGINT,
    folder TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(keyword_id, date, engine_id)
);

-- Create seo_daily_volumes table
CREATE TABLE IF NOT EXISTS seo_daily_volumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword_id BIGINT REFERENCES seo_keywords(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    volume INT,
    engine_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(keyword_id, date, engine_id)
);
